export const API_CONFIG = {
    BASE_URL: 'http://20.244.56.144/evaluation-service',
    ENDPOINTS: {
        STOCKS: '/stocks',
        STOCK_PRICE: '/stocks/{ticker}'
    },
    AUTH: {
        TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzQ3MDU0MTA1LCJpYXQiOjE3NDcwNTM4MDUsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6IjJlM2VhODk2LWZhYmYtNDFmMS05M2NiLTFiNDlmOWVmN2U5NiIsInN1YiI6ImNiLmVuLnU0Y3NlMjI0NTJAY2Iuc3R1ZGVudHMuYW1yaXRhLmVkdSJ9LCJlbWFpbCI6ImNiLmVuLnU0Y3NlMjI0NTJAY2Iuc3R1ZGVudHMuYW1yaXRhLmVkdSIsIm5hbWUiOiJ2YWliaGF2IHNoZWthciIsInJvbGxObyI6ImNiLmVuLnU0Y3NlMjI0NTIiLCJhY2Nlc3NDb2RlIjoiU3d1dUtFIiwiY2xpZW50SUQiOiIyZTNlYTg5Ni1mYWJmLTQxZjEtOTNjYi0xYjQ5ZjllZjdlOTYiLCJjbGllbnRTZWNyZXQiOiJVVG1ZUWNDTkZaZFpOV25RIn0.zga1DbfWX9uZ2jp1ZKhHrQ3qC6KM7vbvX5VXP_nvMdA',
        TOKEN_TYPE: 'Bearer'
    },
    CACHE_TTL: 60000, // 1 minute cache
    MAX_CORRELATION_TICKERS: 2,
    REQUEST_TIMEOUT: 5000 // 5 seconds
};